# Generated by Django 4.1.13 on 2024-07-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmessage',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dmessage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
