# Generated by Django 4.1.13 on 2024-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_dmessage_dislike_alter_dmessage_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
