# Generated by Django 4.1.13 on 2024-07-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_dmessage_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dmessage',
        ),
    ]
